[package]
name = "merry_christmas"
version = "0.1.0"
authors = ["ColdIce <ColdIce@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[dependencies.bevy]
version = "0.4"
features = ["jpeg"]